[package]
name = "rust_etl"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
log = "0.4"
env_logger = "0.10"
serde_json = "1.0"
csv = "1.1"
clap = { version = "4.3", features = ["derive"] }